services:
  # We use Pebble to test certificate auto-provisioning.
  pebble:
    container_name: "boulevard-pebble"
    image: "ghcr.io/letsencrypt/pebble:latest"
    command: >
      -config test/config/pebble-config.json
      -strict
    environment:
      # We disable options that reproduce potential real world issues (such as
      # nonces being rejected) because we are not trying to test
      # go.n16f.net/acme, so no point in adding annoying delays during
      # development and tests.
      PEBBLE_WFE_NONCEREJECT: "0"
      PEBBLE_VA_NOSLEEP: "1"
    # The contain must be able to listen on the host so that it can connect to
    # Boulevard for HTTP challenges.
    network_mode: "host"
  # We use FPM to test FastCGI support.
  fpm:
    container_name: "boulevard-fpm"
    image: "bitnami/php-fpm:8.3"
    ports:
      - "9000:9000"
    volumes:
      - "./docker-compose/fpm:/app/test:ro"
  nginx:
    container_name: "boulevard-nginx"
    image: "nginx:1.27"
    environment:
      NGINX_INSTANCE: "main"
      NGINX_ADDRESS: "127.42.1.1"
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
    # All NGINX instances must listen on the host so that we can listen on
    # multiple local addresses (127.0.0.0/8).
    network_mode: "host"
    volumes:
      - "./docker-compose/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro"
  nginx-i1:
    container_name: "boulevard-nginx-i1"
    image: "nginx:1.27"
    environment:
      NGINX_INSTANCE: "i1"
      NGINX_ADDRESS: "127.42.2.1"
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
    network_mode: "host"
    volumes:
      - "./docker-compose/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro"
  nginx-i2:
    container_name: "boulevard-nginx-i2"
    image: "nginx:1.27"
    environment:
      NGINX_INSTANCE: "i2"
      NGINX_ADDRESS: "127.42.2.2"
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
    network_mode: "host"
    volumes:
      - "./docker-compose/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro"
  nginx-i3:
    container_name: "boulevard-nginx-i3"
    image: "nginx:1.27"
    environment:
      NGINX_INSTANCE: "i3"
      NGINX_ADDRESS: "127.42.2.3"
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
    network_mode: "host"
    volumes:
      - "./docker-compose/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro"
