services:
  # We use Pebble to test certificate auto-provisioning.
  pebble:
    container_name: "boulevard-pebble"
    image: "ghcr.io/letsencrypt/pebble:latest"
    command: >
      -config test/config/pebble-config.json
      -strict
    environment:
      # We disable options that reproduce potential real world issues (such as
      # nonces being rejected) because we are not trying to test
      # go.n16f.net/acme, so no point in adding annoying delays during
      # development and tests.
      PEBBLE_WFE_NONCEREJECT: "0"
      PEBBLE_VA_NOSLEEP: "1"
    # The contain must be able to listen on the host so that it can connect to
    # Boulevard for HTTP challenges.
    network_mode: "host"
  # We use FPM to test FastCGI support.
  fpm:
    container_name: "boulevard-fpm"
    image: "bitnami/php-fpm:8.3"
    ports:
      - "9000:9000"
    volumes:
      - "./docker-compose/fpm:/app/test:ro"
  nginx:
    container_name: "boulevard-nginx"
    image: "nginx:1.27"
    ports:
      - "9002:9002"
    volumes:
      - "./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
